name: Gradle Build
on: {push: {tags: null}}
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: vaccovecrana/gitflow-oss-java-slim@0.9.7
        with:
          orgConfig: https://vacco-oss.s3.us-east-2.amazonaws.com/vacco-oss.json
        env:
          SONATYPE_USER: ${{secrets.SONATYPE_USER}}
          SONATYPE_PASSWORD: ${{secrets.SONATYPE_PASSWORD}}
          MAVEN_SIGNING_PRV: ${{secrets.MAVEN_SIGNING_PRV}}
